# Generated by Django 2.1.5 on 2019-02-06 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workrkopt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Tue', models.BooleanField(default=True)),
                ('TueIn', models.TimeField(blank=True, default='09:00')),
                ('TueOut', models.TimeField(blank=True, default='18:00')),
                ('TueBr1', models.BooleanField(default=True)),
                ('TueBr1In', models.TimeField(blank=True, default='12:00')),
                ('TueBr1Out', models.TimeField(blank=True, default='13:00')),
                ('TueBr2', models.BooleanField(default=False)),
                ('TueBr2In', models.TimeField(blank=True, default='12:00')),
                ('TueBr2Out', models.TimeField(blank=True, default='13:00')),
                ('Wed', models.BooleanField(default=True)),
                ('WedIn', models.TimeField(blank=True, default='09:00')),
                ('WedOut', models.TimeField(blank=True, default='18:00')),
                ('WedBr1', models.BooleanField(default=True)),
                ('WedBr1In', models.TimeField(blank=True, default='12:00')),
                ('WedBr1Out', models.TimeField(blank=True, default='13:00')),
                ('WedBr2', models.BooleanField(default=False)),
                ('WedBr2In', models.TimeField(blank=True, default='12:00')),
                ('WedBr2Out', models.TimeField(blank=True, default='13:00')),
                ('Thu', models.BooleanField(default=True)),
                ('ThuIn', models.TimeField(blank=True, default='09:00')),
                ('ThuOut', models.TimeField(blank=True, default='18:00')),
                ('ThuBr1', models.BooleanField(default=True)),
                ('ThuBr1In', models.TimeField(blank=True, default='12:00')),
                ('ThuBr1Out', models.TimeField(blank=True, default='13:00')),
                ('ThuBr2', models.BooleanField(default=False)),
                ('ThuBr2In', models.TimeField(blank=True, default='12:00')),
                ('ThuBr2Out', models.TimeField(blank=True, default='13:00')),
                ('Fri', models.BooleanField(default=True)),
                ('FriIn', models.TimeField(blank=True, default='09:00')),
                ('FriOut', models.TimeField(blank=True, default='18:00')),
                ('FriBr1', models.BooleanField(default=True)),
                ('FriBr1In', models.TimeField(blank=True, default='12:00')),
                ('FriBr1Out', models.TimeField(blank=True, default='13:00')),
                ('FriBr2', models.BooleanField(default=False)),
                ('FriBr2In', models.TimeField(blank=True, default='12:00')),
                ('FriBr2Out', models.TimeField(blank=True, default='13:00')),
                ('Sat', models.BooleanField(default=True)),
                ('SatIn', models.TimeField(blank=True, default='09:00')),
                ('SatOut', models.TimeField(blank=True, default='18:00')),
                ('SatBr1', models.BooleanField(default=True)),
                ('SatBr1In', models.TimeField(blank=True, default='12:00')),
                ('SatBr1Out', models.TimeField(blank=True, default='13:00')),
                ('SatBr2', models.BooleanField(default=False)),
                ('SatBr2In', models.TimeField(blank=True, default='12:00')),
                ('SatBr2Out', models.TimeField(blank=True, default='13:00')),
                ('Sun', models.BooleanField(default=True)),
                ('SunIn', models.TimeField(blank=True, default='09:00')),
                ('SunOut', models.TimeField(blank=True, default='18:00')),
                ('SunBr1', models.BooleanField(default=True)),
                ('SunBr1In', models.TimeField(blank=True, default='12:00')),
                ('SunBr1Out', models.TimeField(blank=True, default='13:00')),
                ('SunBr2', models.BooleanField(default=False)),
                ('SunBr2In', models.TimeField(blank=True, default='12:00')),
                ('SunBr2Out', models.TimeField(blank=True, default='13:00')),
                ('Mon', models.BooleanField(default=True)),
                ('MonIn', models.TimeField(blank=True, default='09:00')),
                ('MonOut', models.TimeField(blank=True, default='18:00')),
                ('MonBr1', models.BooleanField(default=True)),
                ('MonBr1In', models.TimeField(blank=True, default='12:00')),
                ('MonBr1Out', models.TimeField(blank=True, default='13:00')),
                ('MonBr2', models.BooleanField(default=False)),
                ('MonBr2In', models.TimeField(blank=True, default='12:00')),
                ('MonBr2Out', models.TimeField(blank=True, default='13:00')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Late_Come', models.TimeField(default='00:00', verbose_name='Допустимое время опоздания')),
                ('Early_Leave', models.TimeField(default='00:00', verbose_name='Допустимое время раннего ухода')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=100)),
                ('BirthDate', models.DateTimeField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.FileField(default='default.jpg', upload_to=workrkopt.models.user_directory_path)),
                ('Working', models.BooleanField(default=False)),
                ('Face_Encodings', models.CharField(blank=True, max_length=10000)),
                ('Work_Status', models.BooleanField(default=False)),
                ('Position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workrkopt.Positions')),
                ('Schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workrkopt.Schedules')),
                ('Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workrkopt.Standard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
