# Generated by Django 2.1.5 on 2019-02-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0014_remove_day_last_check_in'),
        ('workrkopt', '0002_auto_20190207_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='Last_Check_In',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facerec.Check'),
        ),
    ]
