# Generated by Django 2.1.5 on 2019-02-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workrkopt', '0003_worker_last_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Last_Check_In',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facerec.Check'),
        ),
    ]
