# Generated by Django 2.1.5 on 2019-02-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workrkopt', '0004_auto_20190211_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to='workrkopt.Schedules'),
        ),
    ]
