# Generated by Django 2.1.5 on 2019-02-06 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workrkopt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField(null=True)),
                ('Start_Time', models.TimeField(default='00:00:00', null=True)),
                ('Finish_Time', models.TimeField(default='00:00:00', null=True)),
                ('Total_Time', models.TimeField(default='00:00:00', null=True)),
                ('Worked_Time', models.TimeField(default='00:00:00', null=True)),
                ('Late_Come', models.TimeField(default='00:00:00', null=True)),
                ('Early_Leave', models.TimeField(default='00:00:00', null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('Last_Check_In', models.TimeField(null=True)),
                ('Worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workrkopt.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='Day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facerec.Day'),
        ),
        migrations.AddField(
            model_name='check',
            name='Worker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workrkopt.Worker'),
        ),
    ]
