# Generated by Django 2.1.5 on 2019-02-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='Finish_Time',
        ),
        migrations.RemoveField(
            model_name='day',
            name='Start_Time',
        ),
    ]
