# Generated by Django 2.1.5 on 2019-02-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workrkopt', '0002_auto_20190207_1517'),
        ('facerec', '0002_auto_20190207_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.TimeField(default='00:00:00', null=True)),
                ('Finish_Time', models.TimeField(default='00:00:00', null=True)),
                ('Total_Time', models.TimeField(default='00:00:00', null=True)),
                ('Worked_Time', models.TimeField(default='00:00:00', null=True)),
                ('Late_Come', models.TimeField(default='00:00:00', null=True)),
                ('Early_Leave', models.TimeField(default='00:00:00', null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('Day', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facerec.Day')),
                ('Worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workrkopt.Worker')),
            ],
        ),
    ]
