# Generated by Django 2.1.5 on 2019-02-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0003_workshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='Day',
        ),
        migrations.AddField(
            model_name='check',
            name='WorkShift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facerec.Day'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='Current',
            field=models.BooleanField(default=False),
        ),
    ]
