# Generated by Django 2.1.5 on 2019-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0004_auto_20190207_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='Current',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
