# Generated by Django 2.1.5 on 2019-02-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0005_auto_20190207_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='WorkShift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facerec.WorkShift'),
        ),
    ]
