# Generated by Django 2.1.5 on 2019-02-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0006_auto_20190207_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='Current',
        ),
    ]
