# Generated by Django 2.1.5 on 2019-02-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0008_auto_20190208_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='Last_Check_In',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
