# Generated by Django 2.1.5 on 2019-02-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0009_day_last_check_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='Last_Check_In',
        ),
        migrations.AddField(
            model_name='check',
            name='Day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facerec.Day'),
        ),
        migrations.AddField(
            model_name='day',
            name='Mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
