# Generated by Django 2.1.5 on 2019-02-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0010_auto_20190208_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='Last_Check_In',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facerec.Check'),
        ),
    ]
