# Generated by Django 2.1.5 on 2019-02-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workrkopt', '0002_auto_20190207_1517'),
        ('facerec', '0011_day_last_check_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worked_Time', models.TimeField(default='00:00:00', null=True)),
                ('Start_Time', models.TimeField(default='00:00:00', null=True)),
                ('Finish_Time', models.TimeField(default='00:00:00', null=True)),
                ('Day', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facerec.Day')),
                ('Worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workrkopt.Worker')),
            ],
        ),
    ]
