# Generated by Django 2.1.5 on 2019-02-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0012_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='Day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='workshift', to='facerec.Day'),
        ),
    ]
