# Generated by Django 2.1.5 on 2019-02-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0013_auto_20190208_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='Last_Check_In',
        ),
    ]
