# Generated by Django 2.1.5 on 2019-02-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0014_remove_day_last_check_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='Worked_Time',
        ),
        migrations.AlterField(
            model_name='day',
            name='Early_Leave',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='Late_Come',
            field=models.TimeField(default=None, null=True),
        ),
    ]
