# Generated by Django 2.1.5 on 2019-02-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0015_auto_20190211_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Worked_Time',
            field=models.DurationField(default=None, null=True),
        ),
    ]
