# Generated by Django 2.1.5 on 2019-02-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0021_auto_20190211_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='Total_Time',
            field=models.DurationField(default='00:00:00', null=True),
        ),
    ]
