# Generated by Django 2.1.5 on 2019-02-11 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0025_auto_20190211_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='Worked_Time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
