# Generated by Django 2.1.5 on 2019-02-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0028_auto_20190211_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='Day',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facerec.Day'),
        ),
        migrations.AlterField(
            model_name='check',
            name='WorkShift',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facerec.WorkShift'),
        ),
        migrations.AlterField(
            model_name='check',
            name='Worker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workrkopt.Worker'),
        ),
    ]
