# Generated by Django 2.1.5 on 2019-02-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0030_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='Status',
        ),
        migrations.AddField(
            model_name='day',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
